### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by corradosantoro** [CANopenTerm/CANopenTerm#84]
There is the following problem when I try to compile it on Linux Ubuntu 22.04.1:

[ 48%] Building C object CMakeFiles/core.dir/src/api/lua_test_report.c.o
In file included from /home/corrado/Progetti_di_Ricerca/AgriMet/software/CANopenTerm/src/core/eds.h:14,
                 from /home/corrado/Progetti_di_Ricerca/AgriMet/software/CANopenTerm/src/api/lua_test_report.c:11:
/home/corrado/Progetti_di_Ricerca/AgriMet/software/CANopenTerm/src/core/codb.h:13:10: fatal error: cJSON.h: No such file or directory
   13 | #include "cJSON.h"
      |          ^~~~~~~~~
compilation terminated.

**Comment by mupfdev** [comment]
I can replicate the problem and have a have a look. Thank you!

**Comment by mupfdev** [comment]
Did you get it to work?
